mov_speed = 5  // quantity per frame
frames_per_blast = 15
last_blast = frames_per_blast

hp = 100
def = 0.1
hp_max = hp
hp_recover_rate = 2
frames_per_recover = 60
last_recover = 0
gamescore = 0
score_per_hit = 12
blast_damage = 5
impact = 250
impacted_speed = 1
explosives = 1
number_shields = 10
shield_speed = 1
shields = []
shield_pos = 0
