image_xscale = 1.5
image_yscale = 1.5

mov_speed = 5  // quantity per frame
frames_per_blast = 20
last_blast = frames_per_blast

hp = 100
def = 0.1
hp_max = hp
hp_recover_rate = 2
frames_per_recover = 60
last_recover = 0
gamescore = 0
score_per_hit = 12
blast_damage = 5
impact = 250
impacted_speed = 1
explosives = 1
number_shields = 20
shield_speed = 1
shields = []
shield_pos = 0
shield_colision_damage = 1
shield_impulse = 50
shield_current_durability = 0
shield_max_durability = 0
shooted = false
cooldown_recover_shooted = 30
shooted_cooldown = 0
